import Link from "next/link";
import { PageHeader } from "@/components/PageHeader";
import { DataTable } from "@/components/DataTable";

type Row = {
  id: string;
  severity: string;
  message: string;
  created: string;
  state: string;
};

export default function AlertsPage() {
  const rows: Row[] = [
    { id: "AL-9001", severity: "High", message: "Follow-up overdue (BP)", created: "1h ago", state: "Open" },
    { id: "AL-9002", severity: "Medium", message: "Missed ANC check-in", created: "6h ago", state: "Open" },
    { id: "AL-9003", severity: "Low", message: "Document pending verification", created: "2d ago", state: "Queued" },
  ];

  return (
    <div className="space-y-6">
      <PageHeader
        title="Alerts"
        description="Escalations and reminders generated by rules and sync signals (placeholder)."
        right={
          <Link
            href="/dashboard/settings/rules"
            className="inline-flex h-10 items-center justify-center rounded-xl bg-zinc-950 px-4 text-sm font-medium text-white shadow-sm hover:bg-zinc-800 dark:bg-zinc-50 dark:text-zinc-950 dark:hover:bg-zinc-200"
          >
            Manage rules
          </Link>
        }
      />

      <DataTable
        caption="Sample alerts (placeholder)"
        columns={[
          { key: "id", header: "ID", className: "w-[120px]" },
          { key: "severity", header: "Severity", className: "w-[120px]" },
          { key: "message", header: "Message" },
          { key: "created", header: "Created", className: "w-[120px]" },
          { key: "state", header: "State", className: "w-[120px]" },
        ]}
        rows={rows}
      />
    </div>
  );
}

